baseURL = "https://mazzaella.com/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
languageCode = "en"
rssLimit = 10
theme = "hugo-texify3"
title = "mazzaella"

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"

[services]
[services.googleAnalytics]
googleAnalytics = "G-2YMZ21XB88"

[params]
title = "mazzaella"
author = "Elliott Claus"
description = "personal website made with hugo"
homepage = "https://github.com/emdashii"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> |
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = ["css/raw.css", "css/csv-table.css"]
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = false
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

[params.commentEngine]
code = """
  <script src="https://giscus.app/client.js"
        data-repo="emdashii/mazzaella"
        data-repo-id="R_kgDONdiRTg"
        data-category="Announcements"
        data-category-id="DIC_kwDONdiRTs4ClOvR"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
  """

[params.buymeacoffee]
code = """
"""


[params.sharingbuttons]
facebook = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."text/org"]
suffixes = ["org"]
delimiter = "."

[mediaTypes."text/markdown"]
suffixes = ["md", "markdown"]
delimiter = "."

[outputFormats]
[outputFormats.MARKDOWN]
mediaType = "text/markdown"
isPlainText = true
baseName = "index"
relativeURLs = true
permalinkable = true

[outputFormats.ORG]
mediaType = "text/org"
isPlainText = true
baseName = "index"
relativeURLs = true
permalinkable = true

[outputs]
home = ["HTML", "RSS"]
page = ["HTML", "MARKDOWN", "ORG"]
