baseURL = 'https://mazzaella.com/'
languageCode = 'en-us'
title = 'mazzaella'

[outputs]
home = ["HTML", "RSS"]
page = ["HTML", "MARKDOWN", "ORG"]  # enables .md and .org endpoints

[mediaTypes]
[mediaTypes."text/org"]
suffixes = ["org"]

[outputFormats]
[outputFormats.ORG]
mediaType = "text/org"
isPlainText = true