[build]
publish = "public"
command = """
npm install -g sass &&
hugo --gc --minify
"""

[build.environment]
HUGO_VERSION = "0.121.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.20"
