[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.139.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.20"         # needed for dart-sass

[[plugins]]
package = "@netlify/plugin-hugo"

[context.production]
command = """
apt-get update && apt-get install -y dart sassc &&
hugo --gc --minify
"""
