[build]
publish = "public"
# command = """
# hugo --gc --minify
# """

[build.environment]
HUGO_VERSION = "0.139.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.20"
NODE_VERSION = "18"

[[redirects]]
from = "/*/*.md"
to = "/:splat/index.md"
status = 200

[[redirects]]
from = "/*/*.org"
to = "/:splat/index.org"
status = 200
