[build]
command = "npm install && hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.139.4"     # use your hugo version
NODE_VERSION = "18"
DART_SASS_VERSION = "1.83.0" # use latest stable

[[redirects]]
from = "/*/*.md"
to = "/:splat/index.md"
status = 200

[[redirects]]
from = "/*/*.org"
to = "/:splat/index.org"
status = 200

[build.processing]
skip_processing = false
